[package]
name = "multibg-sway"
version = "0.1.2"
authors = ["Gergő Sályi <salyigergo94@gmail.com>"]
edition = "2021"
description = "Set a different wallpaper for the background of each Sway workspace"
readme = "README.md"
homepage = "https://github.com/gergo-salyi/multibg-sway"
repository = "https://github.com/gergo-salyi/multibg-sway"
license = "MIT OR Apache-2.0"
keywords = ["wallpaper", "background", "desktop", "wayland", "sway"]
categories = ["command-line-utilities", "multimedia::images"]
exclude = ["PKGBUILD", "patch/fast_image_resize/data"]

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
env_logger = "0.10.0"
fast_image_resize = "2.7.0"
image = "0.24.6"
log = "0.4.17"
mio = { version = "0.8.6", features = ["os-ext", "os-poll"] }
swayipc = "3.0.1"

[dependencies.smithay-client-toolkit]
version = "0.17.0"
default-features = false


# Apply yet unreleased fix for fast_image_resize
# 
# Current releases of fast_image_resize are broken on rust nightly
# https://github.com/Cykooz/fast_image_resize/issues/15
#
# Issue is already fixed on master branch but the new verison is not released yet
# So temporarly use a clone of fast_image_resize current master branch
# as a local git submodule and add this corresponding patch field here
#
# This will be removed once fast_image_resize 2.7.1 is out
[patch.crates-io]
fast_image_resize = { path = "patch/fast_image_resize" }
